FROM node:22-alpine AS build-stage

WORKDIR /app

COPY package.json ./

RUN yarn global add node-gyp && yarn install

ARG NEXT_PUBLIC_STRAPI_API_URL
ARG NEXT_PUBLIC_GRIP_API_URL
ARG NEXT_PUBLIC_GRIP_BROKING_API_URL
ARG NEXT_PUBLIC_ENVIRONMENT
ARG NEXT_PUBLIC_RSA_PUBLIC_KEY

ENV PATH /app/node_modules/.bin:$PATH

ENV NEXT_PUBLIC_STRAPI_API_URL=${NEXT_PUBLIC_STRAPI_API_URL} \
    NEXT_PUBLIC_GRIP_API_URL=${NEXT_PUBLIC_GRIP_API_URL} \
    NEXT_PUBLIC_GRIP_BROKING_API_URL=${NEXT_PUBLIC_GRIP_BROKING_API_URL} \
    NEXT_PUBLIC_ENVIRONMENT=${NEXT_PUBLIC_ENVIRONMENT} \
    NEXT_PUBLIC_RSA_PUBLIC_KEY=${NEXT_PUBLIC_RSA_PUBLIC_KEY}

COPY . .

RUN chmod +x nextdev.sh

RUN yarn build

FROM node:22-alpine AS final-stage

WORKDIR /app

COPY --from=build-stage /app /app

ARG NEXT_PUBLIC_STRAPI_API_URL
ARG NEXT_PUBLIC_GRIP_API_URL
ARG NEXT_PUBLIC_GRIP_BROKING_API_URL
ARG NEXT_PUBLIC_ENVIRONMENT
ARG NEXT_PUBLIC_RSA_PUBLIC_KEY

ENV NODE_OPTIONS="--max-old-space-size=8192" \
    PATH="/app/node_modules/.bin:$PATH" \
    NEXT_PUBLIC_STRAPI_API_URL=${NEXT_PUBLIC_STRAPI_API_URL} \
    NEXT_PUBLIC_GRIP_API_URL=${NEXT_PUBLIC_GRIP_API_URL} \
    NEXT_PUBLIC_GRIP_BROKING_API_URL=${NEXT_PUBLIC_GRIP_BROKING_API_URL} \
    NEXT_PUBLIC_ENVIRONMENT=${NEXT_PUBLIC_ENVIRONMENT} \
    NEXT_PUBLIC_RSA_PUBLIC_KEY=${NEXT_PUBLIC_RSA_PUBLIC_KEY}

#RUN chown -R 1000:3000 /app

#USER 1000

ENTRYPOINT ["yarn", "start"]
