name: PR Change Build

on:
  push:
    branches-ignore:
      - 'develop'
      - 'release/*'
    tags-ignore:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Add caching
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install yarn
        run: npm install -g yarn

      - name: Install deps
        run: yarn install

        # Run Quiet Linter
      - name: Run ESLint
        run: |
          yarn lint . --quiet || {
            echo "::error::Linting failed. Please fix the above errors."
            exit 1
          }

      - name: Build
        run: yarn build
