# This is a basic workflow to help you get started with Actions

name: Style Linter

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches:
      - feature/*
      - fix/*
      - hotfix/**
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41.0.0
        with:
          files: |
            **.css

      # Run other steps when files are changed
      - name: Clear npm cache
        if: steps.changed-files.outputs.all_changed_files_count > 0
        run: npm cache clean --force

      - name: Install yarn
        if: steps.changed-files.outputs.all_changed_files_count > 0
        run: npm install -g yarn

      - name: Install deps
        if: steps.changed-files.outputs.all_changed_files_count > 0
        run: yarn install

      - name: Run Style linter
        if: steps.changed-files.outputs.all_changed_files_count > 0
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            yarn lint:style "**/$file" --custom-formatter @csstools/stylelint-formatter-github
          done
